### ISSUE TITLE
Paginate not work

### ISSUE THREAD

**Issue by brunocascio** [pingpong-labs/admin#21]
Hi,

I change value of perPage to 1, and paginate not work... I see:
searchOrAllPaginated() not send $perPage param, then value is always 10. (default value)
![captura de pantalla 2015-02-19 a las 16 44 09](https://cloud.githubusercontent.com/assets/2397875/6274459/9148647c-b856-11e4-84e7-a07b31eeb73a.png)

**Comment by gravitano** [comment]
Pagination has been improved in version `~2.0`. Try update :)
