### ISSUE TITLE
dependence to intervention/image

### ISSUE THREAD

**Issue by UnrulyNatives** [pingpong-labs/admin#22]
I have "intervention/image": "dev-develop" in my Laravel 5 project. 

when attempting to install your admin package with composer  I get this error:

pingpong/admin 1.1.0 requires intervention/image  ~2 - no matching package found.

Please advise. 

Thx

**Comment by gravitano** [comment]
Hi, sorry for my late response.

Currently, this package is not supported for Laravel 5.
