### ISSUE TITLE
Class 'Pingpong\Menus\Facades\Menu' not found 

### ISSUE THREAD

**Issue by juanleal** [pingpong-labs/admin#23]
* @param string $alias
* @return void
*/
public function load($alias)
{
if (isset($this->aliases[$alias]))
{
return class_alias($this->aliases[$alias], $alias);
}
}

Error when entry url http://localhost:8000/admin

**Comment by juanleal** [comment]
* @param string $alias
    * @return void
    */
    public function load($alias)
    {
    if (isset($this->aliases[$alias]))
    {
    return class_alias($this->aliases[$alias], $alias);
    }
    }

Error when entry url http://localhost:8000/admin

**Comment by gravitano** [comment]
What version are you using?
