### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by Maciekp** [pingpong-labs/admin#24]
Hi, is Pingpong admin panel working with L5?

**Comment by gravitano** [comment]
No, currently this package is not supported for Laravel 5.

**Comment by romannebesnuy** [comment]
You wrote that it wili be supported soon) Can you say when it will be? Thanks

**Comment by gionnivaleriana** [comment]
@romannebesnuy you can the [admin package by SleepingOwl](/sleeping-owl/admin) with my [AdminLTE template](/gionnivaleriana/laravel-adminlte)

**Comment by gravitano** [comment]
I am working on it. Maybe tomorrow would ready for test :)

**Comment by mishbah** [comment]
I can't wait for the latest updates

**Comment by gravitano** [comment]
This package has been tagged to version `2.0.0` for full Laravel 5 support. Thanks!
