### ISSUE TITLE
"artisan admin:migration" not defined

### ISSUE THREAD

**Issue by Tantacula** [pingpong-labs/admin#32]
Hi, command "artisan admin:install" asks for migrations and then fails with error:
Command "admin:migration" is not defined.

**Comment by gravitano** [comment]
Fixed in new version `2.0.2`. Try updating the package by running `composer update`. Thanks!

**Comment by Tantacula** [comment]
There was another bug also, it looks like:

Do you want publish configuration files from pingpong/admin package ? y
Copied File [\vendor\barryvdh\laravel-ide-helper\config\ide-helper.php] To [\config\ide-helper.php]

I suppose pingpong admin config must be named as admin.php? Don't know, maybe bug with not copied config file was in my system only, but if you test this moment too, this would be good.

**Comment by gravitano** [comment]
Yes, the config file must be named `admin.php`. You can re-publish the config file by running `vendor:publish` command.

**Comment by Tantacula** [comment]
I have already copy it, thanx for fast replies. You are realy fastest guy in the world
