### ISSUE TITLE
Can't login to site with 2.1.2

### ISSUE THREAD

**Issue by sakanaproductions** [pingpong-labs/admin#51]
I use pingpong extend in my user model:
class User extends \Pingpong\Admin\Entities\User implements AuthenticatableContract, CanResetPasswordContract, BillableContract

after upgrading on my test site, I'm now unable to login to the site, it comes back with "the credentials do not match our records".  The login works correctly with 2.1.1 which is what I have on my live server.

however, when I go back to the standard extends Model, it works fine:
class User extends Model implements AuthenticatableContract, CanResetPasswordContract, BillableContract

**Comment by dota-web** [comment]
hello~  can you tall me  how to write code  works fine. thinks~
