### ISSUE TITLE
I need to override users routes. Is there possible?

### ISSUE THREAD

**Issue by Soufraz** [pingpong-labs/admin#69]
I need do a verification with users based on my business rules.
But the route admin/users/create actually is in the admin package of pingpong.
And I need point the route to another controller. Or edit (something as a publish) routes or controller of the admin package.
What is the best way to do this in the pingpong admin package.

**Comment by marcoaacoliveira** [comment]
We solved that just adding the "App\Providers\RouteServiceProvider::class" below the 'Pingpong\Admin\Providers\SupportServiceProvider' in config/app.php in the providers array.
